// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Credential struct {
	ID        uuid.UUID `json:"id"`
	AccessID  string    `json:"access_id"`
	SecretKey string    `json:"secret_key"`
}

type Profile struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	Region      string    `json:"region"`
	CredID      uuid.UUID `json:"cred_id"`
	Username    string    `json:"username"`
}

type User struct {
	Username          string       `json:"username"`
	FullName          string       `json:"full_name"`
	HashedPassword    string       `json:"hashed_password"`
	Email             string       `json:"email"`
	PasswordChangedAt sql.NullTime `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
	UpdatedAt         sql.NullTime `json:"updated_at"`
}
